services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: pdf-rag-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_sessions:/app/chroma_sessions
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: pdf-rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always

